development:
  adapter: postgresql
  encoding: unicode
  database: dev_database
  pool: 5
  username: dev
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test_database
  pool: 5
  username: dev
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: prod_database
  pool: 5
  username: dev
  password: